version: '3'

services:
    rabbitmq:
        hostname: rabbitmq_host
        image: rabbitmq:latest
        networks:
            default:
                aliases:
                    - rabbitmq_host
    producer:
        build: .
        command: ["python", "producer.py"]
        volumes:
            - ./producer:/usr/src/app
            - ./common:/usr/src/common
    consumer:
        build: .
        command: ["python", "consumer.py"]
        volumes:
            - ./consumer:/usr/src/app
            - ./common:/usr/src/common
